// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public interface ActivateServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ActivateServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverName = 1;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>int32 testCase = 2;</code>
   */
  int getTestCase();
}
