// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public interface CommitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 view = 1;</code>
   */
  int getView();

  /**
   * <code>int32 sequenceNumber = 2;</code>
   */
  int getSequenceNumber();

  /**
   * <code>string processId = 3;</code>
   */
  java.lang.String getProcessId();
  /**
   * <code>string processId = 3;</code>
   */
  com.google.protobuf.ByteString
      getProcessIdBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>string digest = 5;</code>
   */
  java.lang.String getDigest();
  /**
   * <code>string digest = 5;</code>
   */
  com.google.protobuf.ByteString
      getDigestBytes();

  /**
   * <code>int32 clusterId = 6;</code>
   */
  int getClusterId();

  /**
   * <code>bool abort = 7;</code>
   */
  boolean getAbort();

  /**
   * <code>.Transaction transaction = 8;</code>
   */
  boolean hasTransaction();
  /**
   * <code>.Transaction transaction = 8;</code>
   */
  org.cse535.proto.Transaction getTransaction();
  /**
   * <code>.Transaction transaction = 8;</code>
   */
  org.cse535.proto.TransactionOrBuilder getTransactionOrBuilder();
}
