// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public interface CrossTxnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CrossTxnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string serverName = 2;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>int32 ballotNumber = 3;</code>
   */
  int getBallotNumber();

  /**
   * <code>int32 clusterId = 6;</code>
   */
  int getClusterId();

  /**
   * <code>int32 successPreparesCount = 4;</code>
   */
  int getSuccessPreparesCount();

  /**
   * <code>string failureReason = 5;</code>
   */
  java.lang.String getFailureReason();
  /**
   * <code>string failureReason = 5;</code>
   */
  com.google.protobuf.ByteString
      getFailureReasonBytes();
}
