// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public interface ExecutionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExecutionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 view = 1;</code>
   */
  int getView();

  /**
   * <code>int32 sequenceNumber = 2;</code>
   */
  int getSequenceNumber();

  /**
   * <code>string processId = 3;</code>
   */
  java.lang.String getProcessId();
  /**
   * <code>string processId = 3;</code>
   */
  com.google.protobuf.ByteString
      getProcessIdBytes();

  /**
   * <code>int32 transactionId = 5;</code>
   */
  int getTransactionId();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>bool success = 6;</code>
   */
  boolean getSuccess();

  /**
   * <code>string status = 9;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 9;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 clusterId = 7;</code>
   */
  int getClusterId();

  /**
   * <code>string failureReason = 8;</code>
   */
  java.lang.String getFailureReason();
  /**
   * <code>string failureReason = 8;</code>
   */
  com.google.protobuf.ByteString
      getFailureReasonBytes();
}
