// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public interface ExecutionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExecutionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 transactionNum = 1;</code>
   */
  int getTransactionNum();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();

  /**
   * <code>string serverName = 3;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 3;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();

  /**
   * <code>int32 clusterId = 4;</code>
   */
  int getClusterId();

  /**
   * <code>string failureReason = 5;</code>
   */
  java.lang.String getFailureReason();
  /**
   * <code>string failureReason = 5;</code>
   */
  com.google.protobuf.ByteString
      getFailureReasonBytes();
}
