// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

public final class Pbft2Pc {
  private Pbft2Pc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionInputConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionInputConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TxnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TxnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrossTxnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CrossTxnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrePrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrePrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrePrepareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrePrepareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrePrepareResponse_SyncTransactionsMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrePrepareResponse_SyncTransactionsMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrePrepareResponse_SyncTransactionStatusMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrePrepareResponse_SyncTransactionStatusMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrePrepareResponse_SyncBalancesMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrePrepareResponse_SyncBalancesMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrepareResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrepareResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExecutionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExecutionReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewChangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewChangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ViewChangeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ViewChangeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewViewRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewViewRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NewViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NewViewResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeactivateServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeactivateServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandOutput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandOutput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReShardingInitData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReShardingInitData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReShardingInitData_AccountBalancesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReShardingInitData_AccountBalancesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReShardingData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReShardingData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReShardingData_AccountBalancesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReShardingData_AccountBalancesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReShardingData_NewDataItemClusterConfigEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReShardingData_NewDataItemClusterConfigEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016pbft-2pc.proto\032\037google/protobuf/timest" +
      "amp.proto\032\033google/protobuf/empty.proto\"q" +
      "\n\026TransactionInputConfig\022\021\n\tsetNumber\030\001 " +
      "\001(\005\022!\n\013transaction\030\002 \001(\0132\014.Transaction\022\014" +
      "\n\004view\030\003 \001(\005\022\023\n\013serverNames\030\005 \003(\t\"\310\001\n\013Tr" +
      "ansaction\022\016\n\006sender\030\001 \001(\005\022\020\n\010receiver\030\002 " +
      "\001(\005\022\016\n\006amount\030\003 \001(\005\022\021\n\treceiver2\030\010 \001(\005\022-" +
      "\n\ttimestamp\030\004 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\027\n\017transactionHash\030\005 \001(\t\022\026\n\016transa" +
      "ctionNum\030\006 \001(\005\022\024\n\014isCrossShard\030\007 \001(\010\"2\n\013" +
      "TxnResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nserverNa" +
      "me\030\002 \001(\t\"\225\001\n\020CrossTxnResponse\022\017\n\007success" +
      "\030\001 \001(\010\022\022\n\nserverName\030\002 \001(\t\022\024\n\014ballotNumb" +
      "er\030\003 \001(\005\022\021\n\tclusterId\030\006 \001(\005\022\034\n\024successPr" +
      "eparesCount\030\004 \001(\005\022\025\n\rfailureReason\030\005 \001(\t" +
      "\"\301\001\n\021PrePrepareRequest\022\014\n\004view\030\001 \001(\005\022\026\n\016" +
      "sequenceNumber\030\002 \001(\005\022!\n\013transaction\030\003 \001(" +
      "\0132\014.Transaction\022\021\n\tprocessId\030\004 \001(\t\022-\n\tti" +
      "mestamp\030\005 \001(\0132\032.google.protobuf.Timestam" +
      "p\022\016\n\006digest\030\006 \001(\t\022\021\n\tclusterId\030\007 \001(\005\"\367\004\n" +
      "\022PrePrepareResponse\022\014\n\004view\030\001 \001(\005\022\026\n\016seq" +
      "uenceNumber\030\002 \001(\005\022\021\n\tprocessId\030\003 \001(\t\022\017\n\007" +
      "success\030\004 \001(\010\022\021\n\tclusterId\030\005 \001(\005\022I\n\023sync" +
      "TransactionsMap\030\010 \003(\0132,.PrePrepareRespon" +
      "se.SyncTransactionsMapEntry\022S\n\030syncTrans" +
      "actionStatusMap\030\t \003(\01321.PrePrepareRespon" +
      "se.SyncTransactionStatusMapEntry\022A\n\017sync" +
      "BalancesMap\030\n \003(\0132(.PrePrepareResponse.S" +
      "yncBalancesMapEntry\022\032\n\022acceptedServerNam" +
      "e\030\013 \001(\t\022\022\n\nneedToSync\030\014 \001(\010\022\032\n\022latestBal" +
      "lotNumber\030\r \001(\005\032H\n\030SyncTransactionsMapEn" +
      "try\022\013\n\003key\030\001 \001(\005\022\033\n\005value\030\002 \001(\0132\014.Transa" +
      "ction:\0028\001\032S\n\035SyncTransactionStatusMapEnt" +
      "ry\022\013\n\003key\030\001 \001(\005\022!\n\005value\030\002 \001(\0162\022.Transac" +
      "tionStatus:\0028\001\0326\n\024SyncBalancesMapEntry\022\013" +
      "\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001\"\276\001\n\016Prepa" +
      "reRequest\022\014\n\004view\030\001 \001(\005\022\026\n\016sequenceNumbe" +
      "r\030\002 \001(\005\022\021\n\tprocessId\030\003 \001(\t\022-\n\ttimestamp\030" +
      "\004 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006dig" +
      "est\030\005 \001(\t\022!\n\013transaction\030\006 \001(\0132\014.Transac" +
      "tion\022\021\n\tclusterId\030\007 \001(\005\"n\n\017PrepareRespon" +
      "se\022\014\n\004view\030\001 \001(\005\022\026\n\016sequenceNumber\030\002 \001(\005" +
      "\022\021\n\tprocessId\030\003 \001(\t\022\017\n\007success\030\004 \001(\010\022\021\n\t" +
      "clusterId\030\005 \001(\005\"\314\001\n\rCommitRequest\022\014\n\004vie" +
      "w\030\001 \001(\005\022\026\n\016sequenceNumber\030\002 \001(\005\022\021\n\tproce" +
      "ssId\030\003 \001(\t\022-\n\ttimestamp\030\004 \001(\0132\032.google.p" +
      "rotobuf.Timestamp\022\016\n\006digest\030\005 \001(\t\022\021\n\tclu" +
      "sterId\030\006 \001(\005\022\r\n\005abort\030\007 \001(\010\022!\n\013transacti" +
      "on\030\010 \001(\0132\014.Transaction\"Z\n\016CommitResponse" +
      "\022\014\n\004view\030\001 \001(\005\022\026\n\016sequenceNumber\030\002 \001(\005\022\021" +
      "\n\tprocessId\030\003 \001(\t\022\017\n\007success\030\004 \001(\010\"\332\001\n\016E" +
      "xecutionReply\022\014\n\004view\030\001 \001(\005\022\026\n\016sequenceN" +
      "umber\030\002 \001(\005\022\021\n\tprocessId\030\003 \001(\t\022\025\n\rtransa" +
      "ctionId\030\005 \001(\005\022-\n\ttimestamp\030\004 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\017\n\007success\030\006 \001(\010\022\016\n" +
      "\006status\030\t \001(\t\022\021\n\tclusterId\030\007 \001(\005\022\025\n\rfail" +
      "ureReason\030\010 \001(\t\"c\n\021ViewChangeRequest\022\014\n\004" +
      "view\030\001 \001(\005\022\021\n\tprocessId\030\002 \001(\t\022-\n\ttimesta" +
      "mp\030\003 \001(\0132\032.google.protobuf.Timestamp\"F\n\022" +
      "ViewChangeResponse\022\014\n\004view\030\001 \001(\005\022\021\n\tproc" +
      "essId\030\002 \001(\t\022\017\n\007success\030\003 \001(\010\"\272\001\n\016NewView" +
      "Request\022\014\n\004view\030\001 \001(\005\022\021\n\tprocessId\030\002 \001(\t" +
      "\022-\n\ttimestamp\030\003 \001(\0132\032.google.protobuf.Ti" +
      "mestamp\022.\n\022viewChangeMessages\030\004 \003(\0132\022.Vi" +
      "ewChangeRequest\022(\n\017prepareMessages\030\005 \003(\013" +
      "2\017.PrepareRequest\"C\n\017NewViewResponse\022\014\n\004" +
      "view\030\001 \001(\005\022\021\n\tprocessId\030\002 \001(\t\022\017\n\007success" +
      "\030\003 \001(\010\"=\n\025ActivateServerRequest\022\022\n\nserve" +
      "rName\030\001 \001(\t\022\020\n\010testCase\030\002 \001(\005\"=\n\026Activat" +
      "eServerResponse\022\017\n\007success\030\001 \001(\010\022\022\n\nserv" +
      "erName\030\002 \001(\t\"?\n\027DeactivateServerRequest\022" +
      "\022\n\nserverName\030\001 \001(\t\022\020\n\010testCase\030\002 \001(\005\"?\n" +
      "\030DeactivateServerResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\022\n\nserverName\030\002 \001(\t\"\035\n\014CommandInput\022\r" +
      "\n\005input\030\001 \001(\t\"\037\n\rCommandOutput\022\016\n\006output" +
      "\030\001 \001(\t\"\242\001\n\022ReShardingInitData\022\021\n\tcluster" +
      "Id\030\001 \001(\005\022A\n\017accountBalances\030\002 \003(\0132(.ReSh" +
      "ardingInitData.AccountBalancesEntry\0326\n\024A" +
      "ccountBalancesEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005valu" +
      "e\030\002 \001(\005:\0028\001\"\254\002\n\016ReShardingData\022\021\n\tcluste" +
      "rId\030\001 \001(\005\022=\n\017accountBalances\030\002 \003(\0132$.ReS" +
      "hardingData.AccountBalancesEntry\022O\n\030newD" +
      "ataItemClusterConfig\030\003 \003(\0132-.ReShardingD" +
      "ata.NewDataItemClusterConfigEntry\0326\n\024Acc" +
      "ountBalancesEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030" +
      "\002 \001(\005:\0028\001\032?\n\035NewDataItemClusterConfigEnt" +
      "ry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005:\0028\001*\220\001\n\021T" +
      "ransactionStatus\022\010\n\004None\020\000\022\r\n\tREQUESTED\020" +
      "\001\022\017\n\013PrePREPARED\020\002\022\014\n\010PREPARED\020\003\022\r\n\tCOMM" +
      "ITTED\020\004\022\014\n\010EXECUTED\020\005\022\013\n\007ABORTED\020\006\022\013\n\007PE" +
      "NDING\020\007\022\014\n\010ACCEPTED\020\0102\375\003\n\nLinearPBFT\0222\n\007" +
      "Request\022\027.TransactionInputConfig\032\014.TxnRe" +
      "sponse\"\000\022A\n\021CrossShardRequest\022\027.Transact" +
      "ionInputConfig\032\021.CrossTxnResponse\"\000\0227\n\nP" +
      "rePrepare\022\022.PrePrepareRequest\032\023.PrePrepa" +
      "reResponse\"\000\022.\n\007Prepare\022\017.PrepareRequest" +
      "\032\020.PrepareResponse\"\000\022+\n\006Commit\022\016.CommitR" +
      "equest\032\017.CommitResponse\"\000\022+\n\004Sync\022\017.Prep" +
      "areRequest\032\020.PrepareResponse\"\000\0226\n\tExecRe" +
      "ply\022\017.ExecutionReply\032\026.google.protobuf.E" +
      "mpty\"\000\022E\n\024ReShardingInitiation\022\026.google." +
      "protobuf.Empty\032\023.ReShardingInitData\"\000\0226\n" +
      "\021ReShardingProcess\022\017.ReShardingData\032\016.Co" +
      "mmandOutput\"\0002\222\002\n\017ActivateServers\022C\n\016act" +
      "ivateServer\022\026.ActivateServerRequest\032\027.Ac" +
      "tivateServerResponse\"\000\022I\n\020deactivateServ" +
      "er\022\030.DeactivateServerRequest\032\031.Deactivat" +
      "eServerResponse\"\000\0228\n\rmakeByzantine\022\r.Com" +
      "mandInput\032\026.google.protobuf.Empty\"\000\0225\n\nm" +
      "akeHonest\022\r.CommandInput\032\026.google.protob" +
      "uf.Empty\"\0002\367\001\n\010Commands\022/\n\014printBalance\022" +
      "\r.CommandInput\032\016.CommandOutput\"\000\022+\n\010prin" +
      "tLog\022\r.CommandInput\032\016.CommandOutput\"\000\022*\n" +
      "\007printDB\022\r.CommandInput\032\016.CommandOutput\"" +
      "\000\022.\n\013Performance\022\r.CommandInput\032\016.Comman" +
      "dOutput\"\000\0221\n\016printDatastore\022\r.CommandInp" +
      "ut\032\016.CommandOutput\"\000B\024\n\020org.cse535.proto" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_TransactionInputConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionInputConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionInputConfig_descriptor,
        new java.lang.String[] { "SetNumber", "Transaction", "View", "ServerNames", });
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Amount", "Receiver2", "Timestamp", "TransactionHash", "TransactionNum", "IsCrossShard", });
    internal_static_TxnResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TxnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TxnResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_CrossTxnResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CrossTxnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CrossTxnResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", "BallotNumber", "ClusterId", "SuccessPreparesCount", "FailureReason", });
    internal_static_PrePrepareRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PrePrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrePrepareRequest_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "Transaction", "ProcessId", "Timestamp", "Digest", "ClusterId", });
    internal_static_PrePrepareResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PrePrepareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrePrepareResponse_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "Success", "ClusterId", "SyncTransactionsMap", "SyncTransactionStatusMap", "SyncBalancesMap", "AcceptedServerName", "NeedToSync", "LatestBallotNumber", });
    internal_static_PrePrepareResponse_SyncTransactionsMapEntry_descriptor =
      internal_static_PrePrepareResponse_descriptor.getNestedTypes().get(0);
    internal_static_PrePrepareResponse_SyncTransactionsMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrePrepareResponse_SyncTransactionsMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PrePrepareResponse_SyncTransactionStatusMapEntry_descriptor =
      internal_static_PrePrepareResponse_descriptor.getNestedTypes().get(1);
    internal_static_PrePrepareResponse_SyncTransactionStatusMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrePrepareResponse_SyncTransactionStatusMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PrePrepareResponse_SyncBalancesMapEntry_descriptor =
      internal_static_PrePrepareResponse_descriptor.getNestedTypes().get(2);
    internal_static_PrePrepareResponse_SyncBalancesMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrePrepareResponse_SyncBalancesMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PrepareRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PrepareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareRequest_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "Timestamp", "Digest", "Transaction", "ClusterId", });
    internal_static_PrepareResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PrepareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrepareResponse_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "Success", "ClusterId", });
    internal_static_CommitRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CommitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitRequest_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "Timestamp", "Digest", "ClusterId", "Abort", "Transaction", });
    internal_static_CommitResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_CommitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommitResponse_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "Success", });
    internal_static_ExecutionReply_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ExecutionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExecutionReply_descriptor,
        new java.lang.String[] { "View", "SequenceNumber", "ProcessId", "TransactionId", "Timestamp", "Success", "Status", "ClusterId", "FailureReason", });
    internal_static_ViewChangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ViewChangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ViewChangeRequest_descriptor,
        new java.lang.String[] { "View", "ProcessId", "Timestamp", });
    internal_static_ViewChangeResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_ViewChangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ViewChangeResponse_descriptor,
        new java.lang.String[] { "View", "ProcessId", "Success", });
    internal_static_NewViewRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_NewViewRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewViewRequest_descriptor,
        new java.lang.String[] { "View", "ProcessId", "Timestamp", "ViewChangeMessages", "PrepareMessages", });
    internal_static_NewViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_NewViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NewViewResponse_descriptor,
        new java.lang.String[] { "View", "ProcessId", "Success", });
    internal_static_ActivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ActivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", "TestCase", });
    internal_static_ActivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ActivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_DeactivateServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_DeactivateServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerRequest_descriptor,
        new java.lang.String[] { "ServerName", "TestCase", });
    internal_static_DeactivateServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_DeactivateServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeactivateServerResponse_descriptor,
        new java.lang.String[] { "Success", "ServerName", });
    internal_static_CommandInput_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_CommandInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandInput_descriptor,
        new java.lang.String[] { "Input", });
    internal_static_CommandOutput_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_CommandOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandOutput_descriptor,
        new java.lang.String[] { "Output", });
    internal_static_ReShardingInitData_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_ReShardingInitData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReShardingInitData_descriptor,
        new java.lang.String[] { "ClusterId", "AccountBalances", });
    internal_static_ReShardingInitData_AccountBalancesEntry_descriptor =
      internal_static_ReShardingInitData_descriptor.getNestedTypes().get(0);
    internal_static_ReShardingInitData_AccountBalancesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReShardingInitData_AccountBalancesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ReShardingData_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_ReShardingData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReShardingData_descriptor,
        new java.lang.String[] { "ClusterId", "AccountBalances", "NewDataItemClusterConfig", });
    internal_static_ReShardingData_AccountBalancesEntry_descriptor =
      internal_static_ReShardingData_descriptor.getNestedTypes().get(0);
    internal_static_ReShardingData_AccountBalancesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReShardingData_AccountBalancesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ReShardingData_NewDataItemClusterConfigEntry_descriptor =
      internal_static_ReShardingData_descriptor.getNestedTypes().get(1);
    internal_static_ReShardingData_NewDataItemClusterConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReShardingData_NewDataItemClusterConfigEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
