// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

/**
 * Protobuf type {@code PrepareResponse}
 */
public  final class PrepareResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PrepareResponse)
    PrepareResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrepareResponse.newBuilder() to construct.
  private PrepareResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrepareResponse() {
    ballotNumber_ = 0;
    processId_ = "";
    success_ = false;
    lastAcceptedUncommittedBallotNumber_ = 0;
    lastCommittedBallotNumber_ = 0;
    acceptedServerName_ = "";
    needToSync_ = false;
    latestBallotNumber_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PrepareResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ballotNumber_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            processId_ = s;
            break;
          }
          case 24: {

            success_ = input.readBool();
            break;
          }
          case 34: {
            org.cse535.proto.Transaction.Builder subBuilder = null;
            if (lastAcceptedUncommittedTransaction_ != null) {
              subBuilder = lastAcceptedUncommittedTransaction_.toBuilder();
            }
            lastAcceptedUncommittedTransaction_ = input.readMessage(org.cse535.proto.Transaction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastAcceptedUncommittedTransaction_);
              lastAcceptedUncommittedTransaction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            lastAcceptedUncommittedBallotNumber_ = input.readInt32();
            break;
          }
          case 50: {
            org.cse535.proto.Transaction.Builder subBuilder = null;
            if (lastCommittedTransaction_ != null) {
              subBuilder = lastCommittedTransaction_.toBuilder();
            }
            lastCommittedTransaction_ = input.readMessage(org.cse535.proto.Transaction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastCommittedTransaction_);
              lastCommittedTransaction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 56: {

            lastCommittedBallotNumber_ = input.readInt32();
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              syncTransactionsMap_ = com.google.protobuf.MapField.newMapField(
                  SyncTransactionsMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000080;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, org.cse535.proto.Transaction>
            syncTransactionsMap__ = input.readMessage(
                SyncTransactionsMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            syncTransactionsMap_.getMutableMap().put(
                syncTransactionsMap__.getKey(), syncTransactionsMap__.getValue());
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              syncTransactionStatusMap_ = com.google.protobuf.MapField.newMapField(
                  SyncTransactionStatusMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000100;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            syncTransactionStatusMap__ = input.readMessage(
                SyncTransactionStatusMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            syncTransactionStatusMap_.getMutableMap().put(
                syncTransactionStatusMap__.getKey(), syncTransactionStatusMap__.getValue());
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              syncBalancesMap_ = com.google.protobuf.MapField.newMapField(
                  SyncBalancesMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000200;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            syncBalancesMap__ = input.readMessage(
                SyncBalancesMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            syncBalancesMap_.getMutableMap().put(
                syncBalancesMap__.getKey(), syncBalancesMap__.getValue());
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            acceptedServerName_ = s;
            break;
          }
          case 96: {

            needToSync_ = input.readBool();
            break;
          }
          case 104: {

            latestBallotNumber_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 8:
        return internalGetSyncTransactionsMap();
      case 9:
        return internalGetSyncTransactionStatusMap();
      case 10:
        return internalGetSyncBalancesMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.PrepareResponse.class, org.cse535.proto.PrepareResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BALLOTNUMBER_FIELD_NUMBER = 1;
  private int ballotNumber_;
  /**
   * <code>int32 ballotNumber = 1;</code>
   */
  public int getBallotNumber() {
    return ballotNumber_;
  }

  public static final int PROCESSID_FIELD_NUMBER = 2;
  private volatile java.lang.Object processId_;
  /**
   * <code>string processId = 2;</code>
   */
  public java.lang.String getProcessId() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processId_ = s;
      return s;
    }
  }
  /**
   * <code>string processId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProcessIdBytes() {
    java.lang.Object ref = processId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 3;
  private boolean success_;
  /**
   * <code>bool success = 3;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  public static final int LASTACCEPTEDUNCOMMITTEDTRANSACTION_FIELD_NUMBER = 4;
  private org.cse535.proto.Transaction lastAcceptedUncommittedTransaction_;
  /**
   * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
   */
  public boolean hasLastAcceptedUncommittedTransaction() {
    return lastAcceptedUncommittedTransaction_ != null;
  }
  /**
   * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
   */
  public org.cse535.proto.Transaction getLastAcceptedUncommittedTransaction() {
    return lastAcceptedUncommittedTransaction_ == null ? org.cse535.proto.Transaction.getDefaultInstance() : lastAcceptedUncommittedTransaction_;
  }
  /**
   * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
   */
  public org.cse535.proto.TransactionOrBuilder getLastAcceptedUncommittedTransactionOrBuilder() {
    return getLastAcceptedUncommittedTransaction();
  }

  public static final int LASTACCEPTEDUNCOMMITTEDBALLOTNUMBER_FIELD_NUMBER = 5;
  private int lastAcceptedUncommittedBallotNumber_;
  /**
   * <code>int32 lastAcceptedUncommittedBallotNumber = 5;</code>
   */
  public int getLastAcceptedUncommittedBallotNumber() {
    return lastAcceptedUncommittedBallotNumber_;
  }

  public static final int LASTCOMMITTEDTRANSACTION_FIELD_NUMBER = 6;
  private org.cse535.proto.Transaction lastCommittedTransaction_;
  /**
   * <code>.Transaction lastCommittedTransaction = 6;</code>
   */
  public boolean hasLastCommittedTransaction() {
    return lastCommittedTransaction_ != null;
  }
  /**
   * <code>.Transaction lastCommittedTransaction = 6;</code>
   */
  public org.cse535.proto.Transaction getLastCommittedTransaction() {
    return lastCommittedTransaction_ == null ? org.cse535.proto.Transaction.getDefaultInstance() : lastCommittedTransaction_;
  }
  /**
   * <code>.Transaction lastCommittedTransaction = 6;</code>
   */
  public org.cse535.proto.TransactionOrBuilder getLastCommittedTransactionOrBuilder() {
    return getLastCommittedTransaction();
  }

  public static final int LASTCOMMITTEDBALLOTNUMBER_FIELD_NUMBER = 7;
  private int lastCommittedBallotNumber_;
  /**
   * <code>int32 lastCommittedBallotNumber = 7;</code>
   */
  public int getLastCommittedBallotNumber() {
    return lastCommittedBallotNumber_;
  }

  public static final int SYNCTRANSACTIONSMAP_FIELD_NUMBER = 8;
  private static final class SyncTransactionsMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, org.cse535.proto.Transaction> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, org.cse535.proto.Transaction>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_SyncTransactionsMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.cse535.proto.Transaction.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, org.cse535.proto.Transaction> syncTransactionsMap_;
  private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.Transaction>
  internalGetSyncTransactionsMap() {
    if (syncTransactionsMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SyncTransactionsMapDefaultEntryHolder.defaultEntry);
    }
    return syncTransactionsMap_;
  }

  public int getSyncTransactionsMapCount() {
    return internalGetSyncTransactionsMap().getMap().size();
  }
  /**
   * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
   */

  public boolean containsSyncTransactionsMap(
      int key) {
    
    return internalGetSyncTransactionsMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSyncTransactionsMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> getSyncTransactionsMap() {
    return getSyncTransactionsMapMap();
  }
  /**
   * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
   */

  public java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> getSyncTransactionsMapMap() {
    return internalGetSyncTransactionsMap().getMap();
  }
  /**
   * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
   */

  public org.cse535.proto.Transaction getSyncTransactionsMapOrDefault(
      int key,
      org.cse535.proto.Transaction defaultValue) {
    
    java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> map =
        internalGetSyncTransactionsMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
   */

  public org.cse535.proto.Transaction getSyncTransactionsMapOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> map =
        internalGetSyncTransactionsMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SYNCTRANSACTIONSTATUSMAP_FIELD_NUMBER = 9;
  private static final class SyncTransactionStatusMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_SyncTransactionStatusMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.ENUM,
                org.cse535.proto.TransactionStatus.None.getNumber());
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> syncTransactionStatusMap_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetSyncTransactionStatusMap() {
    if (syncTransactionStatusMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SyncTransactionStatusMapDefaultEntryHolder.defaultEntry);
    }
    return syncTransactionStatusMap_;
  }
  private static final
  com.google.protobuf.Internal.MapAdapter.Converter<
      java.lang.Integer, org.cse535.proto.TransactionStatus> syncTransactionStatusMapValueConverter =
          com.google.protobuf.Internal.MapAdapter.newEnumConverter(
              org.cse535.proto.TransactionStatus.internalGetValueMap(),
              org.cse535.proto.TransactionStatus.UNRECOGNIZED);
  private static final java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
  internalGetAdaptedSyncTransactionStatusMapMap(
      java.util.Map<java.lang.Integer, java.lang.Integer> map) {
    return new com.google.protobuf.Internal.MapAdapter<
        java.lang.Integer, org.cse535.proto.TransactionStatus, java.lang.Integer>(
            map, syncTransactionStatusMapValueConverter);
  }

  public int getSyncTransactionStatusMapCount() {
    return internalGetSyncTransactionStatusMap().getMap().size();
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public boolean containsSyncTransactionStatusMap(
      int key) {
    
    return internalGetSyncTransactionStatusMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSyncTransactionStatusMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
  getSyncTransactionStatusMap() {
    return getSyncTransactionStatusMapMap();
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
  getSyncTransactionStatusMapMap() {
    return internalGetAdaptedSyncTransactionStatusMapMap(
        internalGetSyncTransactionStatusMap().getMap());}
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public org.cse535.proto.TransactionStatus getSyncTransactionStatusMapOrDefault(
      int key,
      org.cse535.proto.TransactionStatus defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncTransactionStatusMap().getMap();
    return map.containsKey(key)
           ? syncTransactionStatusMapValueConverter.doForward(map.get(key))
           : defaultValue;
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public org.cse535.proto.TransactionStatus getSyncTransactionStatusMapOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncTransactionStatusMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return syncTransactionStatusMapValueConverter.doForward(map.get(key));
  }
  /**
   * Use {@link #getSyncTransactionStatusMapValueMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer>
  getSyncTransactionStatusMapValue() {
    return getSyncTransactionStatusMapValueMap();
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer>
  getSyncTransactionStatusMapValueMap() {
    return internalGetSyncTransactionStatusMap().getMap();
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public int getSyncTransactionStatusMapValueOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncTransactionStatusMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
   */

  public int getSyncTransactionStatusMapValueOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncTransactionStatusMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int SYNCBALANCESMAP_FIELD_NUMBER = 10;
  private static final class SyncBalancesMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_SyncBalancesMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> syncBalancesMap_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetSyncBalancesMap() {
    if (syncBalancesMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          SyncBalancesMapDefaultEntryHolder.defaultEntry);
    }
    return syncBalancesMap_;
  }

  public int getSyncBalancesMapCount() {
    return internalGetSyncBalancesMap().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
   */

  public boolean containsSyncBalancesMap(
      int key) {
    
    return internalGetSyncBalancesMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getSyncBalancesMapMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getSyncBalancesMap() {
    return getSyncBalancesMapMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer> getSyncBalancesMapMap() {
    return internalGetSyncBalancesMap().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
   */

  public int getSyncBalancesMapOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncBalancesMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
   */

  public int getSyncBalancesMapOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetSyncBalancesMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ACCEPTEDSERVERNAME_FIELD_NUMBER = 11;
  private volatile java.lang.Object acceptedServerName_;
  /**
   * <pre>
   *Current server name
   * </pre>
   *
   * <code>string acceptedServerName = 11;</code>
   */
  public java.lang.String getAcceptedServerName() {
    java.lang.Object ref = acceptedServerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      acceptedServerName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Current server name
   * </pre>
   *
   * <code>string acceptedServerName = 11;</code>
   */
  public com.google.protobuf.ByteString
      getAcceptedServerNameBytes() {
    java.lang.Object ref = acceptedServerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      acceptedServerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEEDTOSYNC_FIELD_NUMBER = 12;
  private boolean needToSync_;
  /**
   * <code>bool needToSync = 12;</code>
   */
  public boolean getNeedToSync() {
    return needToSync_;
  }

  public static final int LATESTBALLOTNUMBER_FIELD_NUMBER = 13;
  private int latestBallotNumber_;
  /**
   * <code>int32 latestBallotNumber = 13;</code>
   */
  public int getLatestBallotNumber() {
    return latestBallotNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ballotNumber_ != 0) {
      output.writeInt32(1, ballotNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processId_);
    }
    if (success_ != false) {
      output.writeBool(3, success_);
    }
    if (lastAcceptedUncommittedTransaction_ != null) {
      output.writeMessage(4, getLastAcceptedUncommittedTransaction());
    }
    if (lastAcceptedUncommittedBallotNumber_ != 0) {
      output.writeInt32(5, lastAcceptedUncommittedBallotNumber_);
    }
    if (lastCommittedTransaction_ != null) {
      output.writeMessage(6, getLastCommittedTransaction());
    }
    if (lastCommittedBallotNumber_ != 0) {
      output.writeInt32(7, lastCommittedBallotNumber_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetSyncTransactionsMap(),
        SyncTransactionsMapDefaultEntryHolder.defaultEntry,
        8);
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetSyncTransactionStatusMap(),
        SyncTransactionStatusMapDefaultEntryHolder.defaultEntry,
        9);
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetSyncBalancesMap(),
        SyncBalancesMapDefaultEntryHolder.defaultEntry,
        10);
    if (!getAcceptedServerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, acceptedServerName_);
    }
    if (needToSync_ != false) {
      output.writeBool(12, needToSync_);
    }
    if (latestBallotNumber_ != 0) {
      output.writeInt32(13, latestBallotNumber_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ballotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ballotNumber_);
    }
    if (!getProcessIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processId_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, success_);
    }
    if (lastAcceptedUncommittedTransaction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLastAcceptedUncommittedTransaction());
    }
    if (lastAcceptedUncommittedBallotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, lastAcceptedUncommittedBallotNumber_);
    }
    if (lastCommittedTransaction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLastCommittedTransaction());
    }
    if (lastCommittedBallotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, lastCommittedBallotNumber_);
    }
    for (java.util.Map.Entry<java.lang.Integer, org.cse535.proto.Transaction> entry
         : internalGetSyncTransactionsMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, org.cse535.proto.Transaction>
      syncTransactionsMap__ = SyncTransactionsMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, syncTransactionsMap__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetSyncTransactionStatusMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      syncTransactionStatusMap__ = SyncTransactionStatusMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, syncTransactionStatusMap__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetSyncBalancesMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      syncBalancesMap__ = SyncBalancesMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, syncBalancesMap__);
    }
    if (!getAcceptedServerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, acceptedServerName_);
    }
    if (needToSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, needToSync_);
    }
    if (latestBallotNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, latestBallotNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.PrepareResponse)) {
      return super.equals(obj);
    }
    org.cse535.proto.PrepareResponse other = (org.cse535.proto.PrepareResponse) obj;

    boolean result = true;
    result = result && (getBallotNumber()
        == other.getBallotNumber());
    result = result && getProcessId()
        .equals(other.getProcessId());
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && (hasLastAcceptedUncommittedTransaction() == other.hasLastAcceptedUncommittedTransaction());
    if (hasLastAcceptedUncommittedTransaction()) {
      result = result && getLastAcceptedUncommittedTransaction()
          .equals(other.getLastAcceptedUncommittedTransaction());
    }
    result = result && (getLastAcceptedUncommittedBallotNumber()
        == other.getLastAcceptedUncommittedBallotNumber());
    result = result && (hasLastCommittedTransaction() == other.hasLastCommittedTransaction());
    if (hasLastCommittedTransaction()) {
      result = result && getLastCommittedTransaction()
          .equals(other.getLastCommittedTransaction());
    }
    result = result && (getLastCommittedBallotNumber()
        == other.getLastCommittedBallotNumber());
    result = result && internalGetSyncTransactionsMap().equals(
        other.internalGetSyncTransactionsMap());
    result = result && internalGetSyncTransactionStatusMap().equals(
        other.internalGetSyncTransactionStatusMap());
    result = result && internalGetSyncBalancesMap().equals(
        other.internalGetSyncBalancesMap());
    result = result && getAcceptedServerName()
        .equals(other.getAcceptedServerName());
    result = result && (getNeedToSync()
        == other.getNeedToSync());
    result = result && (getLatestBallotNumber()
        == other.getLatestBallotNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BALLOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getBallotNumber();
    hash = (37 * hash) + PROCESSID_FIELD_NUMBER;
    hash = (53 * hash) + getProcessId().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasLastAcceptedUncommittedTransaction()) {
      hash = (37 * hash) + LASTACCEPTEDUNCOMMITTEDTRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getLastAcceptedUncommittedTransaction().hashCode();
    }
    hash = (37 * hash) + LASTACCEPTEDUNCOMMITTEDBALLOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLastAcceptedUncommittedBallotNumber();
    if (hasLastCommittedTransaction()) {
      hash = (37 * hash) + LASTCOMMITTEDTRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getLastCommittedTransaction().hashCode();
    }
    hash = (37 * hash) + LASTCOMMITTEDBALLOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLastCommittedBallotNumber();
    if (!internalGetSyncTransactionsMap().getMap().isEmpty()) {
      hash = (37 * hash) + SYNCTRANSACTIONSMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSyncTransactionsMap().hashCode();
    }
    if (!internalGetSyncTransactionStatusMap().getMap().isEmpty()) {
      hash = (37 * hash) + SYNCTRANSACTIONSTATUSMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSyncTransactionStatusMap().hashCode();
    }
    if (!internalGetSyncBalancesMap().getMap().isEmpty()) {
      hash = (37 * hash) + SYNCBALANCESMAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSyncBalancesMap().hashCode();
    }
    hash = (37 * hash) + ACCEPTEDSERVERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptedServerName().hashCode();
    hash = (37 * hash) + NEEDTOSYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedToSync());
    hash = (37 * hash) + LATESTBALLOTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLatestBallotNumber();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.PrepareResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.PrepareResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.PrepareResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PrepareResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PrepareResponse)
      org.cse535.proto.PrepareResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetSyncTransactionsMap();
        case 9:
          return internalGetSyncTransactionStatusMap();
        case 10:
          return internalGetSyncBalancesMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableSyncTransactionsMap();
        case 9:
          return internalGetMutableSyncTransactionStatusMap();
        case 10:
          return internalGetMutableSyncBalancesMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.PrepareResponse.class, org.cse535.proto.PrepareResponse.Builder.class);
    }

    // Construct using org.cse535.proto.PrepareResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ballotNumber_ = 0;

      processId_ = "";

      success_ = false;

      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        lastAcceptedUncommittedTransaction_ = null;
      } else {
        lastAcceptedUncommittedTransaction_ = null;
        lastAcceptedUncommittedTransactionBuilder_ = null;
      }
      lastAcceptedUncommittedBallotNumber_ = 0;

      if (lastCommittedTransactionBuilder_ == null) {
        lastCommittedTransaction_ = null;
      } else {
        lastCommittedTransaction_ = null;
        lastCommittedTransactionBuilder_ = null;
      }
      lastCommittedBallotNumber_ = 0;

      internalGetMutableSyncTransactionsMap().clear();
      internalGetMutableSyncTransactionStatusMap().clear();
      internalGetMutableSyncBalancesMap().clear();
      acceptedServerName_ = "";

      needToSync_ = false;

      latestBallotNumber_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.Pbft2Pc.internal_static_PrepareResponse_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse getDefaultInstanceForType() {
      return org.cse535.proto.PrepareResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse build() {
      org.cse535.proto.PrepareResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.PrepareResponse buildPartial() {
      org.cse535.proto.PrepareResponse result = new org.cse535.proto.PrepareResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.ballotNumber_ = ballotNumber_;
      result.processId_ = processId_;
      result.success_ = success_;
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        result.lastAcceptedUncommittedTransaction_ = lastAcceptedUncommittedTransaction_;
      } else {
        result.lastAcceptedUncommittedTransaction_ = lastAcceptedUncommittedTransactionBuilder_.build();
      }
      result.lastAcceptedUncommittedBallotNumber_ = lastAcceptedUncommittedBallotNumber_;
      if (lastCommittedTransactionBuilder_ == null) {
        result.lastCommittedTransaction_ = lastCommittedTransaction_;
      } else {
        result.lastCommittedTransaction_ = lastCommittedTransactionBuilder_.build();
      }
      result.lastCommittedBallotNumber_ = lastCommittedBallotNumber_;
      result.syncTransactionsMap_ = internalGetSyncTransactionsMap();
      result.syncTransactionsMap_.makeImmutable();
      result.syncTransactionStatusMap_ = internalGetSyncTransactionStatusMap();
      result.syncTransactionStatusMap_.makeImmutable();
      result.syncBalancesMap_ = internalGetSyncBalancesMap();
      result.syncBalancesMap_.makeImmutable();
      result.acceptedServerName_ = acceptedServerName_;
      result.needToSync_ = needToSync_;
      result.latestBallotNumber_ = latestBallotNumber_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.PrepareResponse) {
        return mergeFrom((org.cse535.proto.PrepareResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.PrepareResponse other) {
      if (other == org.cse535.proto.PrepareResponse.getDefaultInstance()) return this;
      if (other.getBallotNumber() != 0) {
        setBallotNumber(other.getBallotNumber());
      }
      if (!other.getProcessId().isEmpty()) {
        processId_ = other.processId_;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasLastAcceptedUncommittedTransaction()) {
        mergeLastAcceptedUncommittedTransaction(other.getLastAcceptedUncommittedTransaction());
      }
      if (other.getLastAcceptedUncommittedBallotNumber() != 0) {
        setLastAcceptedUncommittedBallotNumber(other.getLastAcceptedUncommittedBallotNumber());
      }
      if (other.hasLastCommittedTransaction()) {
        mergeLastCommittedTransaction(other.getLastCommittedTransaction());
      }
      if (other.getLastCommittedBallotNumber() != 0) {
        setLastCommittedBallotNumber(other.getLastCommittedBallotNumber());
      }
      internalGetMutableSyncTransactionsMap().mergeFrom(
          other.internalGetSyncTransactionsMap());
      internalGetMutableSyncTransactionStatusMap().mergeFrom(
          other.internalGetSyncTransactionStatusMap());
      internalGetMutableSyncBalancesMap().mergeFrom(
          other.internalGetSyncBalancesMap());
      if (!other.getAcceptedServerName().isEmpty()) {
        acceptedServerName_ = other.acceptedServerName_;
        onChanged();
      }
      if (other.getNeedToSync() != false) {
        setNeedToSync(other.getNeedToSync());
      }
      if (other.getLatestBallotNumber() != 0) {
        setLatestBallotNumber(other.getLatestBallotNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.PrepareResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.PrepareResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int ballotNumber_ ;
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public int getBallotNumber() {
      return ballotNumber_;
    }
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public Builder setBallotNumber(int value) {
      
      ballotNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ballotNumber = 1;</code>
     */
    public Builder clearBallotNumber() {
      
      ballotNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object processId_ = "";
    /**
     * <code>string processId = 2;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder clearProcessId() {
      
      processId_ = getDefaultInstance().getProcessId();
      onChanged();
      return this;
    }
    /**
     * <code>string processId = 2;</code>
     */
    public Builder setProcessIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processId_ = value;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 3;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 3;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 3;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private org.cse535.proto.Transaction lastAcceptedUncommittedTransaction_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> lastAcceptedUncommittedTransactionBuilder_;
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public boolean hasLastAcceptedUncommittedTransaction() {
      return lastAcceptedUncommittedTransactionBuilder_ != null || lastAcceptedUncommittedTransaction_ != null;
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public org.cse535.proto.Transaction getLastAcceptedUncommittedTransaction() {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        return lastAcceptedUncommittedTransaction_ == null ? org.cse535.proto.Transaction.getDefaultInstance() : lastAcceptedUncommittedTransaction_;
      } else {
        return lastAcceptedUncommittedTransactionBuilder_.getMessage();
      }
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public Builder setLastAcceptedUncommittedTransaction(org.cse535.proto.Transaction value) {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastAcceptedUncommittedTransaction_ = value;
        onChanged();
      } else {
        lastAcceptedUncommittedTransactionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public Builder setLastAcceptedUncommittedTransaction(
        org.cse535.proto.Transaction.Builder builderForValue) {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        lastAcceptedUncommittedTransaction_ = builderForValue.build();
        onChanged();
      } else {
        lastAcceptedUncommittedTransactionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public Builder mergeLastAcceptedUncommittedTransaction(org.cse535.proto.Transaction value) {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        if (lastAcceptedUncommittedTransaction_ != null) {
          lastAcceptedUncommittedTransaction_ =
            org.cse535.proto.Transaction.newBuilder(lastAcceptedUncommittedTransaction_).mergeFrom(value).buildPartial();
        } else {
          lastAcceptedUncommittedTransaction_ = value;
        }
        onChanged();
      } else {
        lastAcceptedUncommittedTransactionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public Builder clearLastAcceptedUncommittedTransaction() {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        lastAcceptedUncommittedTransaction_ = null;
        onChanged();
      } else {
        lastAcceptedUncommittedTransaction_ = null;
        lastAcceptedUncommittedTransactionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public org.cse535.proto.Transaction.Builder getLastAcceptedUncommittedTransactionBuilder() {
      
      onChanged();
      return getLastAcceptedUncommittedTransactionFieldBuilder().getBuilder();
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    public org.cse535.proto.TransactionOrBuilder getLastAcceptedUncommittedTransactionOrBuilder() {
      if (lastAcceptedUncommittedTransactionBuilder_ != null) {
        return lastAcceptedUncommittedTransactionBuilder_.getMessageOrBuilder();
      } else {
        return lastAcceptedUncommittedTransaction_ == null ?
            org.cse535.proto.Transaction.getDefaultInstance() : lastAcceptedUncommittedTransaction_;
      }
    }
    /**
     * <code>.Transaction lastAcceptedUncommittedTransaction = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> 
        getLastAcceptedUncommittedTransactionFieldBuilder() {
      if (lastAcceptedUncommittedTransactionBuilder_ == null) {
        lastAcceptedUncommittedTransactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder>(
                getLastAcceptedUncommittedTransaction(),
                getParentForChildren(),
                isClean());
        lastAcceptedUncommittedTransaction_ = null;
      }
      return lastAcceptedUncommittedTransactionBuilder_;
    }

    private int lastAcceptedUncommittedBallotNumber_ ;
    /**
     * <code>int32 lastAcceptedUncommittedBallotNumber = 5;</code>
     */
    public int getLastAcceptedUncommittedBallotNumber() {
      return lastAcceptedUncommittedBallotNumber_;
    }
    /**
     * <code>int32 lastAcceptedUncommittedBallotNumber = 5;</code>
     */
    public Builder setLastAcceptedUncommittedBallotNumber(int value) {
      
      lastAcceptedUncommittedBallotNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastAcceptedUncommittedBallotNumber = 5;</code>
     */
    public Builder clearLastAcceptedUncommittedBallotNumber() {
      
      lastAcceptedUncommittedBallotNumber_ = 0;
      onChanged();
      return this;
    }

    private org.cse535.proto.Transaction lastCommittedTransaction_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> lastCommittedTransactionBuilder_;
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public boolean hasLastCommittedTransaction() {
      return lastCommittedTransactionBuilder_ != null || lastCommittedTransaction_ != null;
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public org.cse535.proto.Transaction getLastCommittedTransaction() {
      if (lastCommittedTransactionBuilder_ == null) {
        return lastCommittedTransaction_ == null ? org.cse535.proto.Transaction.getDefaultInstance() : lastCommittedTransaction_;
      } else {
        return lastCommittedTransactionBuilder_.getMessage();
      }
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public Builder setLastCommittedTransaction(org.cse535.proto.Transaction value) {
      if (lastCommittedTransactionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastCommittedTransaction_ = value;
        onChanged();
      } else {
        lastCommittedTransactionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public Builder setLastCommittedTransaction(
        org.cse535.proto.Transaction.Builder builderForValue) {
      if (lastCommittedTransactionBuilder_ == null) {
        lastCommittedTransaction_ = builderForValue.build();
        onChanged();
      } else {
        lastCommittedTransactionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public Builder mergeLastCommittedTransaction(org.cse535.proto.Transaction value) {
      if (lastCommittedTransactionBuilder_ == null) {
        if (lastCommittedTransaction_ != null) {
          lastCommittedTransaction_ =
            org.cse535.proto.Transaction.newBuilder(lastCommittedTransaction_).mergeFrom(value).buildPartial();
        } else {
          lastCommittedTransaction_ = value;
        }
        onChanged();
      } else {
        lastCommittedTransactionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public Builder clearLastCommittedTransaction() {
      if (lastCommittedTransactionBuilder_ == null) {
        lastCommittedTransaction_ = null;
        onChanged();
      } else {
        lastCommittedTransaction_ = null;
        lastCommittedTransactionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public org.cse535.proto.Transaction.Builder getLastCommittedTransactionBuilder() {
      
      onChanged();
      return getLastCommittedTransactionFieldBuilder().getBuilder();
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    public org.cse535.proto.TransactionOrBuilder getLastCommittedTransactionOrBuilder() {
      if (lastCommittedTransactionBuilder_ != null) {
        return lastCommittedTransactionBuilder_.getMessageOrBuilder();
      } else {
        return lastCommittedTransaction_ == null ?
            org.cse535.proto.Transaction.getDefaultInstance() : lastCommittedTransaction_;
      }
    }
    /**
     * <code>.Transaction lastCommittedTransaction = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder> 
        getLastCommittedTransactionFieldBuilder() {
      if (lastCommittedTransactionBuilder_ == null) {
        lastCommittedTransactionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.cse535.proto.Transaction, org.cse535.proto.Transaction.Builder, org.cse535.proto.TransactionOrBuilder>(
                getLastCommittedTransaction(),
                getParentForChildren(),
                isClean());
        lastCommittedTransaction_ = null;
      }
      return lastCommittedTransactionBuilder_;
    }

    private int lastCommittedBallotNumber_ ;
    /**
     * <code>int32 lastCommittedBallotNumber = 7;</code>
     */
    public int getLastCommittedBallotNumber() {
      return lastCommittedBallotNumber_;
    }
    /**
     * <code>int32 lastCommittedBallotNumber = 7;</code>
     */
    public Builder setLastCommittedBallotNumber(int value) {
      
      lastCommittedBallotNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lastCommittedBallotNumber = 7;</code>
     */
    public Builder clearLastCommittedBallotNumber() {
      
      lastCommittedBallotNumber_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, org.cse535.proto.Transaction> syncTransactionsMap_;
    private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.Transaction>
    internalGetSyncTransactionsMap() {
      if (syncTransactionsMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SyncTransactionsMapDefaultEntryHolder.defaultEntry);
      }
      return syncTransactionsMap_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, org.cse535.proto.Transaction>
    internalGetMutableSyncTransactionsMap() {
      onChanged();;
      if (syncTransactionsMap_ == null) {
        syncTransactionsMap_ = com.google.protobuf.MapField.newMapField(
            SyncTransactionsMapDefaultEntryHolder.defaultEntry);
      }
      if (!syncTransactionsMap_.isMutable()) {
        syncTransactionsMap_ = syncTransactionsMap_.copy();
      }
      return syncTransactionsMap_;
    }

    public int getSyncTransactionsMapCount() {
      return internalGetSyncTransactionsMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public boolean containsSyncTransactionsMap(
        int key) {
      
      return internalGetSyncTransactionsMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSyncTransactionsMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> getSyncTransactionsMap() {
      return getSyncTransactionsMapMap();
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> getSyncTransactionsMapMap() {
      return internalGetSyncTransactionsMap().getMap();
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public org.cse535.proto.Transaction getSyncTransactionsMapOrDefault(
        int key,
        org.cse535.proto.Transaction defaultValue) {
      
      java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> map =
          internalGetSyncTransactionsMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public org.cse535.proto.Transaction getSyncTransactionsMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> map =
          internalGetSyncTransactionsMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSyncTransactionsMap() {
      internalGetMutableSyncTransactionsMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public Builder removeSyncTransactionsMap(
        int key) {
      
      internalGetMutableSyncTransactionsMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.Transaction>
    getMutableSyncTransactionsMap() {
      return internalGetMutableSyncTransactionsMap().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */
    public Builder putSyncTransactionsMap(
        int key,
        org.cse535.proto.Transaction value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSyncTransactionsMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, .Transaction&gt; syncTransactionsMap = 8;</code>
     */

    public Builder putAllSyncTransactionsMap(
        java.util.Map<java.lang.Integer, org.cse535.proto.Transaction> values) {
      internalGetMutableSyncTransactionsMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> syncTransactionStatusMap_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetSyncTransactionStatusMap() {
      if (syncTransactionStatusMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SyncTransactionStatusMapDefaultEntryHolder.defaultEntry);
      }
      return syncTransactionStatusMap_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableSyncTransactionStatusMap() {
      onChanged();;
      if (syncTransactionStatusMap_ == null) {
        syncTransactionStatusMap_ = com.google.protobuf.MapField.newMapField(
            SyncTransactionStatusMapDefaultEntryHolder.defaultEntry);
      }
      if (!syncTransactionStatusMap_.isMutable()) {
        syncTransactionStatusMap_ = syncTransactionStatusMap_.copy();
      }
      return syncTransactionStatusMap_;
    }

    public int getSyncTransactionStatusMapCount() {
      return internalGetSyncTransactionStatusMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public boolean containsSyncTransactionStatusMap(
        int key) {
      
      return internalGetSyncTransactionStatusMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSyncTransactionStatusMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
    getSyncTransactionStatusMap() {
      return getSyncTransactionStatusMapMap();
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
    getSyncTransactionStatusMapMap() {
      return internalGetAdaptedSyncTransactionStatusMapMap(
          internalGetSyncTransactionStatusMap().getMap());}
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public org.cse535.proto.TransactionStatus getSyncTransactionStatusMapOrDefault(
        int key,
        org.cse535.proto.TransactionStatus defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncTransactionStatusMap().getMap();
      return map.containsKey(key)
             ? syncTransactionStatusMapValueConverter.doForward(map.get(key))
             : defaultValue;
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public org.cse535.proto.TransactionStatus getSyncTransactionStatusMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncTransactionStatusMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return syncTransactionStatusMapValueConverter.doForward(map.get(key));
    }
    /**
     * Use {@link #getSyncTransactionStatusMapValueMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getSyncTransactionStatusMapValue() {
      return getSyncTransactionStatusMapValueMap();
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getSyncTransactionStatusMapValueMap() {
      return internalGetSyncTransactionStatusMap().getMap();
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public int getSyncTransactionStatusMapValueOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncTransactionStatusMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public int getSyncTransactionStatusMapValueOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncTransactionStatusMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSyncTransactionStatusMap() {
      internalGetMutableSyncTransactionStatusMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */

    public Builder removeSyncTransactionStatusMap(
        int key) {
      
      internalGetMutableSyncTransactionStatusMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus>
    getMutableSyncTransactionStatusMap() {
      return internalGetAdaptedSyncTransactionStatusMapMap(
           internalGetMutableSyncTransactionStatusMap().getMutableMap());
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */
    public Builder putSyncTransactionStatusMap(
        int key,
        org.cse535.proto.TransactionStatus value) {
      
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableSyncTransactionStatusMap().getMutableMap()
          .put(key, syncTransactionStatusMapValueConverter.doBackward(value));
      return this;
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */
    public Builder putAllSyncTransactionStatusMap(
        java.util.Map<java.lang.Integer, org.cse535.proto.TransactionStatus> values) {
      internalGetAdaptedSyncTransactionStatusMapMap(
          internalGetMutableSyncTransactionStatusMap().getMutableMap())
              .putAll(values);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableSyncTransactionStatusMapValue() {
      return internalGetMutableSyncTransactionStatusMap().getMutableMap();
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */
    public Builder putSyncTransactionStatusMapValue(
        int key,
        int value) {
      
      internalGetMutableSyncTransactionStatusMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, .TransactionStatus&gt; syncTransactionStatusMap = 9;</code>
     */
    public Builder putAllSyncTransactionStatusMapValue(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableSyncTransactionStatusMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> syncBalancesMap_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetSyncBalancesMap() {
      if (syncBalancesMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SyncBalancesMapDefaultEntryHolder.defaultEntry);
      }
      return syncBalancesMap_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableSyncBalancesMap() {
      onChanged();;
      if (syncBalancesMap_ == null) {
        syncBalancesMap_ = com.google.protobuf.MapField.newMapField(
            SyncBalancesMapDefaultEntryHolder.defaultEntry);
      }
      if (!syncBalancesMap_.isMutable()) {
        syncBalancesMap_ = syncBalancesMap_.copy();
      }
      return syncBalancesMap_;
    }

    public int getSyncBalancesMapCount() {
      return internalGetSyncBalancesMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public boolean containsSyncBalancesMap(
        int key) {
      
      return internalGetSyncBalancesMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSyncBalancesMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getSyncBalancesMap() {
      return getSyncBalancesMapMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getSyncBalancesMapMap() {
      return internalGetSyncBalancesMap().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public int getSyncBalancesMapOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncBalancesMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public int getSyncBalancesMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetSyncBalancesMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearSyncBalancesMap() {
      internalGetMutableSyncBalancesMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public Builder removeSyncBalancesMap(
        int key) {
      
      internalGetMutableSyncBalancesMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableSyncBalancesMap() {
      return internalGetMutableSyncBalancesMap().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */
    public Builder putSyncBalancesMap(
        int key,
        int value) {
      
      
      internalGetMutableSyncBalancesMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; syncBalancesMap = 10;</code>
     */

    public Builder putAllSyncBalancesMap(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableSyncBalancesMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object acceptedServerName_ = "";
    /**
     * <pre>
     *Current server name
     * </pre>
     *
     * <code>string acceptedServerName = 11;</code>
     */
    public java.lang.String getAcceptedServerName() {
      java.lang.Object ref = acceptedServerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        acceptedServerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Current server name
     * </pre>
     *
     * <code>string acceptedServerName = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptedServerNameBytes() {
      java.lang.Object ref = acceptedServerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        acceptedServerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Current server name
     * </pre>
     *
     * <code>string acceptedServerName = 11;</code>
     */
    public Builder setAcceptedServerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      acceptedServerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current server name
     * </pre>
     *
     * <code>string acceptedServerName = 11;</code>
     */
    public Builder clearAcceptedServerName() {
      
      acceptedServerName_ = getDefaultInstance().getAcceptedServerName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current server name
     * </pre>
     *
     * <code>string acceptedServerName = 11;</code>
     */
    public Builder setAcceptedServerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      acceptedServerName_ = value;
      onChanged();
      return this;
    }

    private boolean needToSync_ ;
    /**
     * <code>bool needToSync = 12;</code>
     */
    public boolean getNeedToSync() {
      return needToSync_;
    }
    /**
     * <code>bool needToSync = 12;</code>
     */
    public Builder setNeedToSync(boolean value) {
      
      needToSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool needToSync = 12;</code>
     */
    public Builder clearNeedToSync() {
      
      needToSync_ = false;
      onChanged();
      return this;
    }

    private int latestBallotNumber_ ;
    /**
     * <code>int32 latestBallotNumber = 13;</code>
     */
    public int getLatestBallotNumber() {
      return latestBallotNumber_;
    }
    /**
     * <code>int32 latestBallotNumber = 13;</code>
     */
    public Builder setLatestBallotNumber(int value) {
      
      latestBallotNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 latestBallotNumber = 13;</code>
     */
    public Builder clearLatestBallotNumber() {
      
      latestBallotNumber_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PrepareResponse)
  }

  // @@protoc_insertion_point(class_scope:PrepareResponse)
  private static final org.cse535.proto.PrepareResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.PrepareResponse();
  }

  public static org.cse535.proto.PrepareResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrepareResponse>
      PARSER = new com.google.protobuf.AbstractParser<PrepareResponse>() {
    @java.lang.Override
    public PrepareResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PrepareResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PrepareResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrepareResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.PrepareResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

