// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

/**
 * Protobuf type {@code ReShardingData}
 */
public  final class ReShardingData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReShardingData)
    ReShardingDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReShardingData.newBuilder() to construct.
  private ReShardingData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReShardingData() {
    clusterId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReShardingData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            clusterId_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              accountBalances_ = com.google.protobuf.MapField.newMapField(
                  AccountBalancesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            accountBalances__ = input.readMessage(
                AccountBalancesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            accountBalances_.getMutableMap().put(
                accountBalances__.getKey(), accountBalances__.getValue());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              newDataItemClusterConfig_ = com.google.protobuf.MapField.newMapField(
                  NewDataItemClusterConfigDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000004;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            newDataItemClusterConfig__ = input.readMessage(
                NewDataItemClusterConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            newDataItemClusterConfig_.getMutableMap().put(
                newDataItemClusterConfig__.getKey(), newDataItemClusterConfig__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetAccountBalances();
      case 3:
        return internalGetNewDataItemClusterConfig();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.ReShardingData.class, org.cse535.proto.ReShardingData.Builder.class);
  }

  private int bitField0_;
  public static final int CLUSTERID_FIELD_NUMBER = 1;
  private int clusterId_;
  /**
   * <code>int32 clusterId = 1;</code>
   */
  public int getClusterId() {
    return clusterId_;
  }

  public static final int ACCOUNTBALANCES_FIELD_NUMBER = 2;
  private static final class AccountBalancesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_AccountBalancesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> accountBalances_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetAccountBalances() {
    if (accountBalances_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AccountBalancesDefaultEntryHolder.defaultEntry);
    }
    return accountBalances_;
  }

  public int getAccountBalancesCount() {
    return internalGetAccountBalances().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public boolean containsAccountBalances(
      int key) {
    
    return internalGetAccountBalances().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAccountBalancesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalances() {
    return getAccountBalancesMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalancesMap() {
    return internalGetAccountBalances().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public int getAccountBalancesOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetAccountBalances().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public int getAccountBalancesOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetAccountBalances().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int NEWDATAITEMCLUSTERCONFIG_FIELD_NUMBER = 3;
  private static final class NewDataItemClusterConfigDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_NewDataItemClusterConfigEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> newDataItemClusterConfig_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetNewDataItemClusterConfig() {
    if (newDataItemClusterConfig_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          NewDataItemClusterConfigDefaultEntryHolder.defaultEntry);
    }
    return newDataItemClusterConfig_;
  }

  public int getNewDataItemClusterConfigCount() {
    return internalGetNewDataItemClusterConfig().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
   */

  public boolean containsNewDataItemClusterConfig(
      int key) {
    
    return internalGetNewDataItemClusterConfig().getMap().containsKey(key);
  }
  /**
   * Use {@link #getNewDataItemClusterConfigMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getNewDataItemClusterConfig() {
    return getNewDataItemClusterConfigMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer> getNewDataItemClusterConfigMap() {
    return internalGetNewDataItemClusterConfig().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
   */

  public int getNewDataItemClusterConfigOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetNewDataItemClusterConfig().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
   */

  public int getNewDataItemClusterConfigOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetNewDataItemClusterConfig().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clusterId_ != 0) {
      output.writeInt32(1, clusterId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetAccountBalances(),
        AccountBalancesDefaultEntryHolder.defaultEntry,
        2);
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetNewDataItemClusterConfig(),
        NewDataItemClusterConfigDefaultEntryHolder.defaultEntry,
        3);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clusterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, clusterId_);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetAccountBalances().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      accountBalances__ = AccountBalancesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, accountBalances__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetNewDataItemClusterConfig().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      newDataItemClusterConfig__ = NewDataItemClusterConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, newDataItemClusterConfig__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.ReShardingData)) {
      return super.equals(obj);
    }
    org.cse535.proto.ReShardingData other = (org.cse535.proto.ReShardingData) obj;

    boolean result = true;
    result = result && (getClusterId()
        == other.getClusterId());
    result = result && internalGetAccountBalances().equals(
        other.internalGetAccountBalances());
    result = result && internalGetNewDataItemClusterConfig().equals(
        other.internalGetNewDataItemClusterConfig());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterId();
    if (!internalGetAccountBalances().getMap().isEmpty()) {
      hash = (37 * hash) + ACCOUNTBALANCES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAccountBalances().hashCode();
    }
    if (!internalGetNewDataItemClusterConfig().getMap().isEmpty()) {
      hash = (37 * hash) + NEWDATAITEMCLUSTERCONFIG_FIELD_NUMBER;
      hash = (53 * hash) + internalGetNewDataItemClusterConfig().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.ReShardingData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.ReShardingData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReShardingData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReShardingData)
      org.cse535.proto.ReShardingDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetAccountBalances();
        case 3:
          return internalGetNewDataItemClusterConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableAccountBalances();
        case 3:
          return internalGetMutableNewDataItemClusterConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.ReShardingData.class, org.cse535.proto.ReShardingData.Builder.class);
    }

    // Construct using org.cse535.proto.ReShardingData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clusterId_ = 0;

      internalGetMutableAccountBalances().clear();
      internalGetMutableNewDataItemClusterConfig().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingData_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingData getDefaultInstanceForType() {
      return org.cse535.proto.ReShardingData.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingData build() {
      org.cse535.proto.ReShardingData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingData buildPartial() {
      org.cse535.proto.ReShardingData result = new org.cse535.proto.ReShardingData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.clusterId_ = clusterId_;
      result.accountBalances_ = internalGetAccountBalances();
      result.accountBalances_.makeImmutable();
      result.newDataItemClusterConfig_ = internalGetNewDataItemClusterConfig();
      result.newDataItemClusterConfig_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.ReShardingData) {
        return mergeFrom((org.cse535.proto.ReShardingData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.ReShardingData other) {
      if (other == org.cse535.proto.ReShardingData.getDefaultInstance()) return this;
      if (other.getClusterId() != 0) {
        setClusterId(other.getClusterId());
      }
      internalGetMutableAccountBalances().mergeFrom(
          other.internalGetAccountBalances());
      internalGetMutableNewDataItemClusterConfig().mergeFrom(
          other.internalGetNewDataItemClusterConfig());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.ReShardingData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.ReShardingData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int clusterId_ ;
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public int getClusterId() {
      return clusterId_;
    }
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public Builder setClusterId(int value) {
      
      clusterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public Builder clearClusterId() {
      
      clusterId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> accountBalances_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetAccountBalances() {
      if (accountBalances_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AccountBalancesDefaultEntryHolder.defaultEntry);
      }
      return accountBalances_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableAccountBalances() {
      onChanged();;
      if (accountBalances_ == null) {
        accountBalances_ = com.google.protobuf.MapField.newMapField(
            AccountBalancesDefaultEntryHolder.defaultEntry);
      }
      if (!accountBalances_.isMutable()) {
        accountBalances_ = accountBalances_.copy();
      }
      return accountBalances_;
    }

    public int getAccountBalancesCount() {
      return internalGetAccountBalances().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public boolean containsAccountBalances(
        int key) {
      
      return internalGetAccountBalances().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAccountBalancesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalances() {
      return getAccountBalancesMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalancesMap() {
      return internalGetAccountBalances().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public int getAccountBalancesOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetAccountBalances().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public int getAccountBalancesOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetAccountBalances().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAccountBalances() {
      internalGetMutableAccountBalances().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public Builder removeAccountBalances(
        int key) {
      
      internalGetMutableAccountBalances().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableAccountBalances() {
      return internalGetMutableAccountBalances().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */
    public Builder putAccountBalances(
        int key,
        int value) {
      
      
      internalGetMutableAccountBalances().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public Builder putAllAccountBalances(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableAccountBalances().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> newDataItemClusterConfig_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetNewDataItemClusterConfig() {
      if (newDataItemClusterConfig_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NewDataItemClusterConfigDefaultEntryHolder.defaultEntry);
      }
      return newDataItemClusterConfig_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableNewDataItemClusterConfig() {
      onChanged();;
      if (newDataItemClusterConfig_ == null) {
        newDataItemClusterConfig_ = com.google.protobuf.MapField.newMapField(
            NewDataItemClusterConfigDefaultEntryHolder.defaultEntry);
      }
      if (!newDataItemClusterConfig_.isMutable()) {
        newDataItemClusterConfig_ = newDataItemClusterConfig_.copy();
      }
      return newDataItemClusterConfig_;
    }

    public int getNewDataItemClusterConfigCount() {
      return internalGetNewDataItemClusterConfig().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public boolean containsNewDataItemClusterConfig(
        int key) {
      
      return internalGetNewDataItemClusterConfig().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNewDataItemClusterConfigMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getNewDataItemClusterConfig() {
      return getNewDataItemClusterConfigMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getNewDataItemClusterConfigMap() {
      return internalGetNewDataItemClusterConfig().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public int getNewDataItemClusterConfigOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetNewDataItemClusterConfig().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public int getNewDataItemClusterConfigOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetNewDataItemClusterConfig().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearNewDataItemClusterConfig() {
      internalGetMutableNewDataItemClusterConfig().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public Builder removeNewDataItemClusterConfig(
        int key) {
      
      internalGetMutableNewDataItemClusterConfig().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableNewDataItemClusterConfig() {
      return internalGetMutableNewDataItemClusterConfig().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */
    public Builder putNewDataItemClusterConfig(
        int key,
        int value) {
      
      
      internalGetMutableNewDataItemClusterConfig().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; newDataItemClusterConfig = 3;</code>
     */

    public Builder putAllNewDataItemClusterConfig(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableNewDataItemClusterConfig().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReShardingData)
  }

  // @@protoc_insertion_point(class_scope:ReShardingData)
  private static final org.cse535.proto.ReShardingData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.ReShardingData();
  }

  public static org.cse535.proto.ReShardingData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReShardingData>
      PARSER = new com.google.protobuf.AbstractParser<ReShardingData>() {
    @java.lang.Override
    public ReShardingData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReShardingData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReShardingData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReShardingData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.ReShardingData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

