// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

/**
 * Protobuf type {@code ReShardingInitData}
 */
public  final class ReShardingInitData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReShardingInitData)
    ReShardingInitDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReShardingInitData.newBuilder() to construct.
  private ReShardingInitData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReShardingInitData() {
    clusterId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReShardingInitData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            clusterId_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              accountBalances_ = com.google.protobuf.MapField.newMapField(
                  AccountBalancesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            accountBalances__ = input.readMessage(
                AccountBalancesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            accountBalances_.getMutableMap().put(
                accountBalances__.getKey(), accountBalances__.getValue());
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetAccountBalances();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.cse535.proto.ReShardingInitData.class, org.cse535.proto.ReShardingInitData.Builder.class);
  }

  private int bitField0_;
  public static final int CLUSTERID_FIELD_NUMBER = 1;
  private int clusterId_;
  /**
   * <code>int32 clusterId = 1;</code>
   */
  public int getClusterId() {
    return clusterId_;
  }

  public static final int ACCOUNTBALANCES_FIELD_NUMBER = 2;
  private static final class AccountBalancesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_AccountBalancesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> accountBalances_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetAccountBalances() {
    if (accountBalances_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AccountBalancesDefaultEntryHolder.defaultEntry);
    }
    return accountBalances_;
  }

  public int getAccountBalancesCount() {
    return internalGetAccountBalances().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public boolean containsAccountBalances(
      int key) {
    
    return internalGetAccountBalances().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAccountBalancesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalances() {
    return getAccountBalancesMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalancesMap() {
    return internalGetAccountBalances().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public int getAccountBalancesOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetAccountBalances().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
   */

  public int getAccountBalancesOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetAccountBalances().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clusterId_ != 0) {
      output.writeInt32(1, clusterId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetAccountBalances(),
        AccountBalancesDefaultEntryHolder.defaultEntry,
        2);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clusterId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, clusterId_);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetAccountBalances().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      accountBalances__ = AccountBalancesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, accountBalances__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.cse535.proto.ReShardingInitData)) {
      return super.equals(obj);
    }
    org.cse535.proto.ReShardingInitData other = (org.cse535.proto.ReShardingInitData) obj;

    boolean result = true;
    result = result && (getClusterId()
        == other.getClusterId());
    result = result && internalGetAccountBalances().equals(
        other.internalGetAccountBalances());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTERID_FIELD_NUMBER;
    hash = (53 * hash) + getClusterId();
    if (!internalGetAccountBalances().getMap().isEmpty()) {
      hash = (37 * hash) + ACCOUNTBALANCES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAccountBalances().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.cse535.proto.ReShardingInitData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingInitData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingInitData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.cse535.proto.ReShardingInitData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.cse535.proto.ReShardingInitData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReShardingInitData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReShardingInitData)
      org.cse535.proto.ReShardingInitDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetAccountBalances();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableAccountBalances();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.cse535.proto.ReShardingInitData.class, org.cse535.proto.ReShardingInitData.Builder.class);
    }

    // Construct using org.cse535.proto.ReShardingInitData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clusterId_ = 0;

      internalGetMutableAccountBalances().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.cse535.proto.Pbft2Pc.internal_static_ReShardingInitData_descriptor;
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingInitData getDefaultInstanceForType() {
      return org.cse535.proto.ReShardingInitData.getDefaultInstance();
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingInitData build() {
      org.cse535.proto.ReShardingInitData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.cse535.proto.ReShardingInitData buildPartial() {
      org.cse535.proto.ReShardingInitData result = new org.cse535.proto.ReShardingInitData(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.clusterId_ = clusterId_;
      result.accountBalances_ = internalGetAccountBalances();
      result.accountBalances_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.cse535.proto.ReShardingInitData) {
        return mergeFrom((org.cse535.proto.ReShardingInitData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.cse535.proto.ReShardingInitData other) {
      if (other == org.cse535.proto.ReShardingInitData.getDefaultInstance()) return this;
      if (other.getClusterId() != 0) {
        setClusterId(other.getClusterId());
      }
      internalGetMutableAccountBalances().mergeFrom(
          other.internalGetAccountBalances());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.cse535.proto.ReShardingInitData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.cse535.proto.ReShardingInitData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int clusterId_ ;
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public int getClusterId() {
      return clusterId_;
    }
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public Builder setClusterId(int value) {
      
      clusterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clusterId = 1;</code>
     */
    public Builder clearClusterId() {
      
      clusterId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> accountBalances_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetAccountBalances() {
      if (accountBalances_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AccountBalancesDefaultEntryHolder.defaultEntry);
      }
      return accountBalances_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableAccountBalances() {
      onChanged();;
      if (accountBalances_ == null) {
        accountBalances_ = com.google.protobuf.MapField.newMapField(
            AccountBalancesDefaultEntryHolder.defaultEntry);
      }
      if (!accountBalances_.isMutable()) {
        accountBalances_ = accountBalances_.copy();
      }
      return accountBalances_;
    }

    public int getAccountBalancesCount() {
      return internalGetAccountBalances().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public boolean containsAccountBalances(
        int key) {
      
      return internalGetAccountBalances().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAccountBalancesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalances() {
      return getAccountBalancesMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getAccountBalancesMap() {
      return internalGetAccountBalances().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public int getAccountBalancesOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetAccountBalances().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public int getAccountBalancesOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetAccountBalances().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAccountBalances() {
      internalGetMutableAccountBalances().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public Builder removeAccountBalances(
        int key) {
      
      internalGetMutableAccountBalances().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableAccountBalances() {
      return internalGetMutableAccountBalances().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */
    public Builder putAccountBalances(
        int key,
        int value) {
      
      
      internalGetMutableAccountBalances().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; accountBalances = 2;</code>
     */

    public Builder putAllAccountBalances(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableAccountBalances().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReShardingInitData)
  }

  // @@protoc_insertion_point(class_scope:ReShardingInitData)
  private static final org.cse535.proto.ReShardingInitData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.cse535.proto.ReShardingInitData();
  }

  public static org.cse535.proto.ReShardingInitData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReShardingInitData>
      PARSER = new com.google.protobuf.AbstractParser<ReShardingInitData>() {
    @java.lang.Override
    public ReShardingInitData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReShardingInitData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReShardingInitData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReShardingInitData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.cse535.proto.ReShardingInitData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

