// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbft-2pc.proto

package org.cse535.proto;

/**
 * Protobuf enum {@code TransactionStatus}
 */
public enum TransactionStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>None = 0;</code>
   */
  None(0),
  /**
   * <code>REQUESTED = 1;</code>
   */
  REQUESTED(1),
  /**
   * <code>PrePREPARED = 2;</code>
   */
  PrePREPARED(2),
  /**
   * <code>PREPARED = 3;</code>
   */
  PREPARED(3),
  /**
   * <code>COMMITTED = 4;</code>
   */
  COMMITTED(4),
  /**
   * <code>EXECUTED = 5;</code>
   */
  EXECUTED(5),
  /**
   * <code>ABORTED = 6;</code>
   */
  ABORTED(6),
  /**
   * <code>PENDING = 7;</code>
   */
  PENDING(7),
  /**
   * <code>ACCEPTED = 8;</code>
   */
  ACCEPTED(8),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>None = 0;</code>
   */
  public static final int None_VALUE = 0;
  /**
   * <code>REQUESTED = 1;</code>
   */
  public static final int REQUESTED_VALUE = 1;
  /**
   * <code>PrePREPARED = 2;</code>
   */
  public static final int PrePREPARED_VALUE = 2;
  /**
   * <code>PREPARED = 3;</code>
   */
  public static final int PREPARED_VALUE = 3;
  /**
   * <code>COMMITTED = 4;</code>
   */
  public static final int COMMITTED_VALUE = 4;
  /**
   * <code>EXECUTED = 5;</code>
   */
  public static final int EXECUTED_VALUE = 5;
  /**
   * <code>ABORTED = 6;</code>
   */
  public static final int ABORTED_VALUE = 6;
  /**
   * <code>PENDING = 7;</code>
   */
  public static final int PENDING_VALUE = 7;
  /**
   * <code>ACCEPTED = 8;</code>
   */
  public static final int ACCEPTED_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TransactionStatus valueOf(int value) {
    return forNumber(value);
  }

  public static TransactionStatus forNumber(int value) {
    switch (value) {
      case 0: return None;
      case 1: return REQUESTED;
      case 2: return PrePREPARED;
      case 3: return PREPARED;
      case 4: return COMMITTED;
      case 5: return EXECUTED;
      case 6: return ABORTED;
      case 7: return PENDING;
      case 8: return ACCEPTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TransactionStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TransactionStatus>() {
          public TransactionStatus findValueByNumber(int number) {
            return TransactionStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.cse535.proto.Pbft2Pc.getDescriptor().getEnumTypes().get(0);
  }

  private static final TransactionStatus[] VALUES = values();

  public static TransactionStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TransactionStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:TransactionStatus)
}

